// ============================================================
//  MLS — KADER, abgeleitet aus den Torschützen-Quoten
//
//  ERZEUGTE DATEI — nicht von Hand bearbeiten.
//  Wächst mit:  npm run odds:holen -- mls --schuetzen
//
//  Stand:       2026-07-29T23:28:38.870Z
//  Beobachtete Spiele: 16
//  Zugeordnet:  0 von 494 Spielern (0 %)
//
//  Es gibt KEINE Kaderquelle. Die Quoten sind der Kader: ein Buchmacher
//  bepreist keinen Verletzten. Der Verein steckt in der Schnittmenge —
//  wer in zwei Spielen desselben Klubs mit verschiedenen Gegnern
//  vorkommt, ist eindeutig. Bis dahin bleibt er offen und wird nicht
//  angeboten: ein Spieler bei der falschen Mannschaft wäre ein stiller
//  Fehler, der erst bei der Abrechnung auffällt.
// ============================================================

export const ZUORDNUNG = {};

export const BEOBACHTUNGEN = [
 {
  "home": "Portland Timbers",
  "away": "Seattle Sounders FC",
  "kickoff": "2026-08-02T02:30:00Z",
  "spieler": [
   "Kevin Kelsy",
   "Felipe Mora",
   "Danny Musovski",
   "Osaze De Rosario",
   "Kristoffer Velde",
   "Albert Rusnák",
   "Ariel Lassiter",
   "Paul Rothrock",
   "Jesús Ferreira",
   "David Costa",
   "Antony Alves Santos",
   "Paul Arriola",
   "Snyder Brunell",
   "Jimer Fory",
   "Hassani Dotson",
   "Brandon Bye",
   "Kalani Kossarienzi",
   "Diego Chará",
   "Jackson Ragen",
   "Kamal Miller",
   "Finn Surman",
   "Nouhou Tolo",
   "Stuart Hawkins",
   "Alex Bonetig",
   "Antino Lopez",
   "Zac McGraw",
   "Sawyer Jura",
   "Ian Smith",
   "Sebastian Gomez",
   "Eric Miller",
   "Joao Ortiz",
   "Yéimar Gómez",
   "Gage Guerra",
   "Alex Roldan",
   "Juan Mosquera",
   "Cristian Roldan",
   "Pedro de la Vega"
  ]
 },
 {
  "home": "New York City FC",
  "away": "Toronto FC",
  "kickoff": "2026-07-31T23:30:00Z",
  "spieler": [
   "Talles Magno",
   "Hannes Wolf",
   "Malachi Jones",
   "Agustín Ojeda",
   "Deandre Kerr",
   "Djordje Mihailovic",
   "Theo Corbeanu",
   "Derrick Etienne Jr.",
   "Andrés Perea",
   "Jonathan  Shore",
   "Jonathan Osorio",
   "Tayvon Gray",
   "Kai Trewin",
   "Richie Laryea",
   "Alonso Coello",
   "Walker Zimmerman",
   "Thiago Martins",
   "James Sands",
   "Kobe Franklin",
   "Nico Cavallo",
   "Zane Monlouis",
   "Seymour Reid",
   "Máximo Carrizo",
   "Keaton Parks",
   "Mitja Ilenic",
   "Nicksoen Gomis",
   "Kevin O'Toole",
   "Alonso Martínez",
   "Nicolás Fernández",
   "Raul Gustavo",
   "Jules-Anthony Vilsaint",
   "No Scorer"
  ]
 },
 {
  "home": "Philadelphia Union",
  "away": "Atlanta United FC",
  "kickoff": "2026-08-01T23:30:00Z",
  "spieler": [
   "Milan Iloski",
   "Bruno Damiani",
   "Emmanuel Latte Lath",
   "Cavan Sullivan",
   "Quinn Sullivan",
   "Indiana Vassilev",
   "Aleksei Miranchuk",
   "Miguel Almirón",
   "Ben Bender",
   "Danley Jean Jacques",
   "Luke Brennan",
   "Jesús Bueno",
   "Jovan Lukic",
   "Francis Westfield",
   "Nathan Harriel",
   "Neil Pierre",
   "Tristan Muyumba",
   "Olwethu Makhanya",
   "Kai Wagner",
   "Japhet Sery",
   "Stian Gregersen",
   "Tomás Jacob",
   "Ronald Hernández",
   "Enea Mihaj",
   "Steven Alzate",
   "Pedro Amador",
   "Jeremy Rafanello",
   "Augustin Anello",
   "Matthew Edwards",
   "Will Reilly",
   "Finn Sundstrom",
   "Adrian Gill",
   "Alejandro Bedoya",
   "Cayman Togashi",
   "No Scorer"
  ]
 },
 {
  "home": "CF Montreal",
  "away": "New England Revolution",
  "kickoff": "2026-08-01T23:30:00Z",
  "spieler": [
   "Dor Turgeman",
   "Carles Gil",
   "Hennadii Synchuk",
   "Luca Langoni",
   "Griffin Yow",
   "Noah Streit",
   "Peyton Miller",
   "Fabian Herbers",
   "Alhassan Yusuf",
   "Victor Loturi",
   "Jackson Yueill",
   "Brayan Vera",
   "Brayan Ceballos",
   "Matthew Polster",
   "Brooklyn Raines",
   "Luca Petrasso",
   "Samuel Piette",
   "Efraín Morales",
   "Jalen Neal",
   "Dawid Bugaj",
   "Mamadou Fofana",
   "Will Sands",
   "Dagur Thorhallsson",
   "Tanner Beason",
   "Brandan Craig",
   "Allan Oyirwoth",
   "Damario Mcintosh",
   "Eric Klein",
   "Prince Osei Owusu",
   "No Scorer"
  ]
 },
 {
  "home": "Inter Miami CF",
  "away": "Columbus Crew SC",
  "kickoff": "2026-08-01T23:30:00Z",
  "spieler": [
   "Lionel Messi",
   "Luis Suárez",
   "Mateo Silvetti",
   "Telasco Segovia",
   "Rodrigo De Paul",
   "Taha Habroune",
   "Max Arfsten",
   "Yannick Bright",
   "Marcelo Herrera",
   "Ian Fray",
   "Mohamed Farsi",
   "Dylan Chambost",
   "Sean Zawadzki",
   "Facundo Mura",
   "Micael",
   "Malte Amundsen",
   "Noah Allen",
   "Rudy Camacho",
   "Steven Moreira",
   "Amar Sejdic",
   "Sékou Tidiany Bangoura",
   "David Ruiz",
   "Owen Presthus",
   "Tristan Brown",
   "Chase Adams",
   "Cesar Ruvalcaba",
   "Ricardo Montenegro",
   "Andrés Herrera",
   "Israel Boatwright",
   "Tyler Hall",
   "Germán Berterame",
   "Gonzalo Luján",
   "Santiago Morales",
   "Maximiliano Falcón",
   "Tadeo Allende",
   "David Ayala",
   "André Gomes",
   "No Scorer"
  ]
 },
 {
  "home": "D.C. United",
  "away": "Nashville SC",
  "kickoff": "2026-08-01T23:30:00Z",
  "spieler": [
   "Sam Surridge",
   "Louis Munteanu",
   "Hany Mukhtar",
   "Shakur Mohammed",
   "Jackson Hopkins",
   "Joao Peglow",
   "Ahmed Qasem",
   "Jared Stroud",
   "Jordan Knight",
   "Alex Muyl",
   "Hosei Kijima",
   "Bryan Acosta",
   "Matti Peltola",
   "Matthew Corcoran",
   "Edvard Tagseth",
   "Brandon Servania",
   "Joshua Bauer",
   "Andy Najar",
   "Silvan Hefti",
   "Jeisson Palacios",
   "Lucas Bartlett",
   "Sean Nealis",
   "Kye Rowles",
   "Daniel Lovitz",
   "Jack Maher",
   "Caden Clark",
   "Woobens Pacius",
   "Garrison Tubbs",
   "Jacob Murrell",
   "Gavin Turner",
   "Charles-Emile Brunet",
   "Warren Madrigal",
   "Cristian Espinoza",
   "Conner Antley",
   "No Scorer"
  ]
 },
 {
  "home": "FC Cincinnati",
  "away": "San Jose Earthquakes",
  "kickoff": "2026-08-01T23:30:00Z",
  "spieler": [
   "Kévin Denkey",
   "Preston Judd",
   "Evander",
   "Timo Werner",
   "Ayoub Jabbari",
   "Kenji Mboma Dem",
   "Ousseni Bouda",
   "Jack Skahan",
   "Nick Fernandez",
   "Beau Leroux",
   "Paul Marie",
   "Pavel Bucha",
   "Jamar Ricketts",
   "Ian Harkes",
   "Bryan Ramirez",
   "Kyle Smith",
   "Daniel Munie",
   "Obinna Nwobodo",
   "Nick Hagglund",
   "Dave Romney",
   "Reid Roberts",
   "Matt Miazga",
   "Miles Robinson",
   "Benjamin Kikanovic",
   "Stefan Chirila",
   "Alvas Powell",
   "Stiven Jimenez",
   "Brian Anunga",
   "Teenage Hadebe",
   "Max Floriani",
   "Vítor Costa de Brito",
   "Andrei Chirila",
   "Edwyn Mendoza",
   "No Scorer"
  ]
 },
 {
  "home": "Vancouver Whitecaps FC",
  "away": "Los Angeles FC",
  "kickoff": "2026-08-01T23:30:00Z",
  "spieler": [
   "Brian White",
   "Ryan Gauld",
   "Thomas Müller",
   "Denis Bouanga",
   "David Martínez",
   "Jeevan Badwal",
   "Mathias  Laborda",
   "Oliver Larraz",
   "Timothy Tillman",
   "Édier Ocampo",
   "Ryan Hollingshead",
   "Andrés Cubas",
   "Mihail Gherasimencov",
   "Tristan Blackmon",
   "Ranko Veselinović",
   "Nkosi Tafari",
   "Tate Johnson",
   "Eddie Segura",
   "Aaron Long",
   "Jean Claude Ngando",
   "Ryan Raposo",
   "Liam Mackenzie",
   "Kenny Nielsen",
   "Johnny Selemani",
   "Sam Adekugbe",
   "Sergi Palencia",
   "No Scorer"
  ]
 },
 {
  "home": "New York Red Bulls",
  "away": "Orlando City SC",
  "kickoff": "2026-08-01T23:30:00Z",
  "spieler": [
   "Eric Maxim Choupo-Moting",
   "Martin Ojeda",
   "Julian Hall",
   "Jorge Ruvalcaba",
   "Cade Cowell",
   "Emil Forsberg",
   "Mohammed Sofo",
   "Marco Pasalic",
   "Tyrese Spicer",
   "Iván Angulo",
   "Adri Mehmeti",
   "Ronald  Donkor",
   "Griffin Dorsey",
   "Eduard Atuesta",
   "Braian Ojeda",
   "Dylan Nealis",
   "David Brekalo",
   "Omar Valencia",
   "Iago Teodoro",
   "Robin Jansson",
   "Robert Voloder",
   "Justin Che",
   "Andy Rojas",
   "Roald Mitchell",
   "Harvey Sarajian",
   "Rafael Mosquera",
   "Cameron Harper",
   "Zakaria Taifi",
   "Tahir Reid-Brown",
   "Wilder Cartagena",
   "Tim Parker",
   "Dennis Gjengaar",
   "Joran Gerbet",
   "No Scorer"
  ]
 },
 {
  "home": "Chicago Fire",
  "away": "Charlotte FC",
  "kickoff": "2026-08-02T00:30:00Z",
  "spieler": [
   "Philip Zinckernagel",
   "Robin Lod",
   "Maren Haile-Selassie",
   "Jonathan Bamba",
   "Idan Gorno",
   "Liel Abada",
   "Pep Biel",
   "Archie Goodwin",
   "Dylan Borso",
   "Andrew Gutman",
   "Tyger Smalls",
   "Anton Saletros",
   "Mauricio Pineda",
   "Leonardo Barroso",
   "Sergio Oregel",
   "Jack Elliott",
   "Luca de la Torre",
   "Joel Waterman",
   "Brandt Bronico",
   "Jonathan Dean",
   "Ashley Westwood",
   "Harry Toffolo",
   "Djibril Diani",
   "Viktor Radojevic",
   "Tim Ream",
   "Andrew Privett",
   "Nathan Byrne",
   "Kerwin Vargas",
   "Mbekezeli Mbokazi",
   "No Scorer"
  ]
 },
 {
  "home": "Sporting Kansas City",
  "away": "Houston Dynamo",
  "kickoff": "2026-08-02T00:30:00Z",
  "spieler": [
   "Dejan Joveljic",
   "Ezequiel Ponce",
   "Guilherme Augusto",
   "Stephen Afrifa",
   "Ondrej Lingr",
   "Mateusz Bogusz",
   "Calvin Harris",
   "Shapi Suleymanov",
   "Jack McGlynn",
   "Lawrence Ennali",
   "Duane Holmes",
   "Manu García",
   "Jake Davis",
   "Héctor Herrera",
   "Lasse Berg Johnsen",
   "Jacob Bartlett",
   "Jose De Lima Junior",
   "Erik Sviatchenko",
   "Zorhan Bassong",
   "Lucas Halter",
   "Wyatt Meyer",
   "Ethan Bartlow",
   "Ian James",
   "Jansen Miller",
   "Ibrahim Aliyu",
   "Agustín Bouzat",
   "Franco Negri",
   "Justin Reynolds",
   "Nelson Quiñones",
   "Antônio Carlos",
   "No Scorer"
  ]
 },
 {
  "home": "Minnesota United FC",
  "away": "San Diego FC",
  "kickoff": "2026-08-02T00:30:00Z",
  "spieler": [
   "Onni Valakari",
   "Tomás Chancalay",
   "Carlos Harvey",
   "Kelvin Yeboah",
   "Aníbal Godoy",
   "Joaquín Pereyra",
   "Andrés Reyes",
   "Jordan Adebayo-Smith",
   "Alex Mighten",
   "Bongokuhle Hlongwane",
   "DJ Taylor",
   "Morris Duggan",
   "William Kumado",
   "Owen Gene",
   "Alejandro Alvarado Jr.",
   "Jefferson Díaz",
   "Anthony Markanich",
   "Devin Padelford",
   "Marcus Caldeira",
   "Oscar Verhoeven",
   "Luca Bombino",
   "Marcus Ingvartsen",
   "Manu Duah",
   "Wilson Eisner",
   "Ian Pilcher",
   "Kieran Chandler",
   "Jeppe Tverskov",
   "Wil Trapp",
   "Emmanuel Boateng",
   "Hirving Lozano",
   "Michael Boxall",
   "Anders Dreyer",
   "Christopher McVey",
   "Nicolás Romero",
   "No Scorer"
  ]
 },
 {
  "home": "St. Louis City SC",
  "away": "Real Salt Lake",
  "kickoff": "2026-08-02T00:30:00Z",
  "spieler": [
   "Simon Becher",
   "Victor Olatunji",
   "Marcel Hartel",
   "Jeong Sang-Bin",
   "Diego Luna",
   "Zavier Gozo",
   "Eduard Löwen",
   "Zach Booth",
   "Conrad Wallem",
   "Stijn Spierings",
   "Chris Durkin",
   "Daniel Edelman",
   "Tomas Totland",
   "Juan Manuel Sanabria",
   "Noel Caliskan",
   "Timo Baumgartl",
   "Lukas Engel",
   "Dante Polvara",
   "Sam Junqua",
   "Juan Arias",
   "DeAndre Yedlin",
   "Philip Quinton",
   "Aiden Hezarkhani",
   "Tomas Ostrak",
   "MyKhi Joyner",
   "Miguel Perez",
   "Dominik Marczuk",
   "Pablo Ruiz",
   "Mamadou Fall",
   "Alexandros Katranis",
   "Griffin Dillon",
   "Kyle Hiebert",
   "Justen Glad",
   "Kobi Henry",
   "Caden Glover",
   "Tyson Charles Pearce",
   "Luca Moisa",
   "Brendan McSorley",
   "Omar Marquez",
   "Chukwuemeka Eneli",
   "No Scorer"
  ]
 },
 {
  "home": "Colorado Rapids",
  "away": "Austin FC",
  "kickoff": "2026-08-02T01:30:00Z",
  "spieler": [
   "Rafael Navarro",
   "Donavan Phillip",
   "Dante Sealy",
   "Darren Yapi",
   "Paxten Aaronson",
   "Myrto Uzuni",
   "Brandon Vázquez",
   "Facundo Torres",
   "Wayne Frederick",
   "Alex Harris",
   "Besard Sabovic",
   "Ali Fadal",
   "Bryce Jamison",
   "Owen Wolff",
   "Jon Gallagher",
   "Lucas Herrington",
   "Joshua Atencio",
   "Noah Cobb",
   "Keegan Rosenberry",
   "Reggie Cannon",
   "Nicolás Dubersarsky",
   "Guilherme Biro",
   "Miguel Navarro",
   "Oleksandr Svatok",
   "Brendan Hines-Ike",
   "Ilie Sánchez",
   "Zan Kolmanic",
   "CJ Fodrey",
   "Jackson Travis",
   "Micah Burton",
   "No Scorer"
  ]
 },
 {
  "home": "LA Galaxy",
  "away": "FC Dallas",
  "kickoff": "2026-08-02T02:30:00Z",
  "spieler": [
   "Petar Musa",
   "Joseph Paintsil",
   "Marco Reus",
   "Logan Farrington",
   "Anderson Julio",
   "Patrickson Delgado",
   "Bernard Kamungo",
   "Elijah Wynder",
   "Lucas Sanabria",
   "Ran Binyamin",
   "Kaick",
   "Maya Yoshida",
   "Edwin Cerrillo",
   "Shaq Moore",
   "Nolan Norris",
   "Jakob Glesnes",
   "Miki Yamane",
   "Carlos Garcés",
   "Osaze Urhoghide",
   "John Nelson",
   "Sebastien Ibeagha",
   "Julián Aude",
   "Lalas Abubakar",
   "Louicius Don Deedson",
   "Chris Rindov",
   "Ruben Ramos Jr",
   "Diego García",
   "Daniel Baran",
   "Harbor Miller",
   "Álvaro Augusto",
   "Enzo Newman",
   "Joshua Torquato",
   "Isaiah Parente",
   "Ramiro",
   "Erik Thommy",
   "No Scorer"
  ]
 },
 {
  "home": "Portland Timbers",
  "away": "Seattle Sounders FC",
  "kickoff": "2026-08-02T02:45:00Z",
  "spieler": [
   "Kevin Kelsy",
   "Felipe Mora",
   "Danny Musovski",
   "Osaze De Rosario",
   "Kristoffer Velde",
   "Albert Rusnák",
   "Ariel Lassiter",
   "Paul Rothrock",
   "Jesús Ferreira",
   "David Costa",
   "Antony Alves Santos",
   "Paul Arriola",
   "Snyder Brunell",
   "Jimer Fory",
   "Hassani Dotson",
   "Brandon Bye",
   "Kalani Kossarienzi",
   "Diego Chará",
   "Jackson Ragen",
   "Kamal Miller",
   "Finn Surman",
   "Nouhou Tolo",
   "Stuart Hawkins",
   "Alex Bonetig",
   "Antino Lopez",
   "Zac McGraw",
   "Sawyer Jura",
   "Ian Smith",
   "Sebastian Gomez",
   "Eric Miller",
   "Joao Ortiz",
   "Yéimar Gómez",
   "Gage Guerra",
   "Alex Roldan",
   "Juan Mosquera",
   "Cristian Roldan",
   "Pedro de la Vega",
   "No Scorer",
   "Kim Kee-Hee"
  ]
 }
];
